//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.MIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInfo
    {
        public DeviceInfo()
        {
            this.PointPicture = new HashSet<PointPicture>();
        }
    
        public int Id { get; set; }
        public string DeviceName { get; set; }
        public string ShuCaiNum { get; set; }
        public string SensorNum { get; set; }
        public string PhoneNum { get; set; }
        public string YaoshiNum { get; set; }
        public decimal DeviceLon { get; set; }
        public decimal DeviceLat { get; set; }
        public string MonitorType { get; set; }
        public string MonitorName { get; set; }
        public int MonitorPointInfoId { get; set; }
        public string Beizhu { get; set; }
    
        public virtual MonitorPointInfo MonitorPointInfo { get; set; }
        public virtual ICollection<PointPicture> PointPicture { get; set; }
    }
}
